version: '3.8'

services:
  # 1. THE WEB SERVER (Your App)
  web:
    # Use the image you just pushed to Docker Hub
    image: vineet46/vehicles24:latest
    restart: always
    ports:
      - "80:80"  
    depends_on:
      - mysql

  # 2. THE DATABASE
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: vehicles24
      MYSQL_USER: vehicles24_user
      MYSQL_PASSWORD: vehicles24_pass
    volumes:
      - db_data:/var/lib/mysql 
      - /opt/app/vehicle.sql:/docker-entrypoint-initdb.d/vehicle.sql:ro
      - /opt/app/deployment/uploads:/var/www/html/upload
      

volumes:
  db_data: